// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Goal")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("NumberOfMeals")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Preferences")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Models.Entities.DailyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalCarbs")
                        .HasColumnType("float");

                    b.Property<double>("TotalFat")
                        .HasColumnType("float");

                    b.Property<double>("TotalKcal")
                        .HasColumnType("float");

                    b.Property<double>("TotalProtein")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("DailyLogs");
                });

            modelBuilder.Entity("Models.Entities.DailyLogMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyLogId")
                        .HasColumnType("int");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCalories")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DailyLogId");

                    b.ToTable("DailyLogMeals");
                });

            modelBuilder.Entity("Models.Entities.DailyLogRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ConsumptionMultiplier")
                        .HasColumnType("float");

                    b.Property<int>("DailyLogMealId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("QuantityConsumedInGrams")
                        .HasColumnType("float");

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DailyLogMealId");

                    b.HasIndex("FoodId");

                    b.ToTable("DailyLogRecipes");
                });

            modelBuilder.Entity("Models.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Carbs")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fat")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("bit");

                    b.Property<double>("Kcal")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<double>("StandardServingSizeInGrams")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Carbs = 1.3999999999999999,
                            Description = "Mic dejun clasic cu două ouă bătute și prăjite în ulei de măsline. O opțiune rapidă și bogată în proteine pentru a începe ziua.",
                            Fat = 19.0,
                            ImageUrl = "reteta1.jpg",
                            IsVegan = false,
                            IsVegetarian = true,
                            Kcal = 286.0,
                            Name = "Omletă simplă",
                            Protein = 25.199999999999999,
                            StandardServingSizeInGrams = 130.0
                        },
                        new
                        {
                            Id = 102,
                            Carbs = 42.700000000000003,
                            Description = "O masă de bază pentru sportivi. Piept de pui fraged, preparat simplu la grătar sau fiert, servit alături de o porție generoasă de orez alb fiert.",
                            Fat = 5.2000000000000002,
                            ImageUrl = "reteta2.jpg",
                            IsVegan = false,
                            IsVegetarian = false,
                            Kcal = 425.0,
                            Name = "Pui și Orez ",
                            Protein = 38.700000000000003,
                            StandardServingSizeInGrams = 350.0
                        },
                        new
                        {
                            Id = 103,
                            Carbs = 7.7999999999999998,
                            Description = "O salată proaspătă și sățioasă, cu bucăți de ton în apă, roșii proaspete tăiate cubulețe și un strop de ulei de măsline extravirgin.",
                            Fat = 12.0,
                            ImageUrl = "reteta3.jpg",
                            IsVegan = false,
                            IsVegetarian = false,
                            Kcal = 260.0,
                            Name = "Salată de Ton",
                            Protein = 26.399999999999999,
                            StandardServingSizeInGrams = 205.0
                        },
                        new
                        {
                            Id = 104,
                            Carbs = 50.0,
                            Description = "Gustarea clasică, perfectă pentru un plus de energie. Două felii de pâine integrală unse cu un strat generos de unt de arahide cremos.",
                            Fat = 15.0,
                            ImageUrl = "reteta4.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            Kcal = 350.0,
                            Name = "Pâine cu Unt de Arahide",
                            Protein = 16.0,
                            StandardServingSizeInGrams = 125.0
                        },
                        new
                        {
                            Id = 105,
                            Carbs = 27.0,
                            Description = "Un bol cremos de iaurt grecesc 2%, bogat în proteine, amestecat cu o banană proaspătă tăiată felii. Ideal pentru mic dejun sau o gustare rapidă.",
                            Fat = 4.5,
                            ImageUrl = "reteta5.jpg",
                            IsVegan = false,
                            IsVegetarian = true,
                            Kcal = 200.0,
                            Name = "Iaurt Grecesc cu Banane",
                            Protein = 14.5,
                            StandardServingSizeInGrams = 250.0
                        },
                        new
                        {
                            Id = 106,
                            Carbs = 45.0,
                            Description = "O tortilla integrală umplută cu o varietate de legume proaspete (salată, roșii, ardei) și o bază de hummus. Ideal pentru vegetarieni și vegani.",
                            Fat = 10.0,
                            ImageUrl = "reteta6.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            Kcal = 300.0,
                            Name = "Wrap Vegetarian",
                            Protein = 8.0,
                            StandardServingSizeInGrams = 200.0
                        },
                        new
                        {
                            Id = 107,
                            Carbs = 7.0,
                            Description = "O masă curată, bogată în proteine și fibre. Piept de pui la grătar servit alături de buchețele de broccoli preparate la abur sau trase ușor la tigaie.",
                            Fat = 15.0,
                            ImageUrl = "reteta7.jpg",
                            IsVegan = false,
                            IsVegetarian = false,
                            Kcal = 320.0,
                            Name = "Pui și Broccoli",
                            Protein = 35.0,
                            StandardServingSizeInGrams = 270.0
                        },
                        new
                        {
                            Id = 108,
                            Carbs = 90.0,
                            Description = "O porție consistentă de chili vegan, plină de fasole neagră, porumb și condimente, servită peste un pat de orez fiert. O masă completă și sățioasă.",
                            Fat = 12.0,
                            ImageUrl = "reteta8.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            Kcal = 610.0,
                            Name = "Chili Vegetarian (mare)",
                            Protein = 35.0,
                            StandardServingSizeInGrams = 450.0
                        },
                        new
                        {
                            Id = 109,
                            Carbs = 40.0,
                            Description = "Un wrap gigant pentru cei care au nevoie de proteine. O tortilla mare umplută cu 200g de piept de pui, mozzarella topită și felii de avocado.",
                            Fat = 38.0,
                            ImageUrl = "reteta9.jpg",
                            IsVegan = false,
                            IsVegetarian = false,
                            Kcal = 750.0,
                            Name = "Wrap Proteic XXL",
                            Protein = 65.0,
                            StandardServingSizeInGrams = 350.0
                        },
                        new
                        {
                            Id = 110,
                            Carbs = 40.0,
                            Description = "Un mic dejun sau prânz mediteranean sățios. Conține ouă fierte, roșii proaspete, avocado cremos și un strop de ulei de măsline.",
                            Fat = 36.0,
                            ImageUrl = "reteta10.jpg",
                            IsVegan = false,
                            IsVegetarian = true,
                            Kcal = 660.0,
                            Name = "Bol Grecesc cu Ouă",
                            Protein = 38.0,
                            StandardServingSizeInGrams = 400.0
                        },
                        new
                        {
                            Id = 111,
                            Carbs = 70.0,
                            Description = "O salată vegană plină de nutrienți. Bază de quinoa fiartă, năut, roșii, castraveți și o vinegretă simplă de lămâie și ulei de măsline.",
                            Fat = 20.0,
                            ImageUrl = "reteta11.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            Kcal = 560.0,
                            Name = "Salată Quinoa și Năut",
                            Protein = 22.0,
                            StandardServingSizeInGrams = 410.0
                        },
                        new
                        {
                            Id = 112,
                            Carbs = 30.0,
                            Description = "Gustarea crocantă și dulce-sărată perfectă. Un măr proaspăt, tăiat felii, servit cu o porție de unt de arahide pentru dipp.",
                            Fat = 16.0,
                            ImageUrl = "reteta12.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            Kcal = 280.0,
                            Name = "Măr cu Unt de Arahide",
                            Protein = 7.0,
                            StandardServingSizeInGrams = 175.0
                        },
                        new
                        {
                            Id = 113,
                            Carbs = 18.0,
                            Description = "O gustare vegană, preparată peste noapte. Semințe de chia înmuiate în lapte de migdale (sau alt lapte vegetal) până devin o budincă gelatinoasă.",
                            Fat = 13.0,
                            ImageUrl = "reteta13.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            Kcal = 210.0,
                            Name = "Budincă de Chia",
                            Protein = 6.0,
                            StandardServingSizeInGrams = 150.0
                        },
                        new
                        {
                            Id = 114,
                            Carbs = 17.0,
                            Description = "Gustare vegană clasică, bogată în fibre și vitamine. Hummus cremos din năut, servit cu bastonașe de morcov proaspăt.",
                            Fat = 8.0,
                            ImageUrl = "reteta14.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            Kcal = 170.0,
                            Name = "Hummus cu Morcovi",
                            Protein = 5.0,
                            StandardServingSizeInGrams = 150.0
                        },
                        new
                        {
                            Id = 115,
                            Carbs = 46.0,
                            Description = "Un mic dejun sau o gustare rapidă, emblematică. O felie de pâine integrală prăjită, acoperită cu avocado pasat și un praf de sare și piper.",
                            Fat = 8.0,
                            ImageUrl = "reteta15.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            Kcal = 295.0,
                            Name = "Avocado Toast",
                            Protein = 14.0,
                            StandardServingSizeInGrams = 130.0
                        },
                        new
                        {
                            Id = 116,
                            Carbs = 6.0,
                            Description = "O salată italiană clasică, proaspătă și ușoară. Conține doar roșii coapte, mozzarella proaspătă (low-fat) și un strop de ulei de măsline.",
                            Fat = 24.0,
                            ImageUrl = "reteta16.jpg",
                            IsVegan = false,
                            IsVegetarian = true,
                            Kcal = 356.0,
                            Name = "Salată Caprese Simplă",
                            Protein = 29.0,
                            StandardServingSizeInGrams = 210.0
                        },
                        new
                        {
                            Id = 117,
                            Carbs = 75.0,
                            Description = "O porție decadentă de paste clasice, preparate cu ou, bacon (guanciale sau pancetta) și o cantitate generoasă de smântână pentru gătit.",
                            Fat = 55.0,
                            ImageUrl = "reteta17.jpg",
                            IsVegan = false,
                            IsVegetarian = false,
                            Kcal = 950.0,
                            Name = "Paste Carbonara",
                            Protein = 45.0,
                            StandardServingSizeInGrams = 350.0
                        },
                        new
                        {
                            Id = 118,
                            Carbs = 11.0,
                            Description = "O salată cu foarte puțini carbohidrați, dar extrem de sățioasă. Conține ouă fierte, avocado, bacon prăjit și bucăți de mozzarella, totul pe un pat de verdeață.",
                            Fat = 52.0,
                            ImageUrl = "reteta18.jpg",
                            IsVegan = false,
                            IsVegetarian = false,
                            Kcal = 698.0,
                            Name = "Salată Keto",
                            Protein = 47.0,
                            StandardServingSizeInGrams = 300.0
                        });
                });

            modelBuilder.Entity("Models.Entities.FoodIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<double>("QuantityInGrams")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("IngredientId");

                    b.ToTable("FoodIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FoodId = 101,
                            IngredientId = 1,
                            QuantityInGrams = 120.0
                        },
                        new
                        {
                            Id = 2,
                            FoodId = 101,
                            IngredientId = 6,
                            QuantityInGrams = 10.0
                        },
                        new
                        {
                            Id = 3,
                            FoodId = 102,
                            IngredientId = 2,
                            QuantityInGrams = 150.0
                        },
                        new
                        {
                            Id = 4,
                            FoodId = 102,
                            IngredientId = 3,
                            QuantityInGrams = 200.0
                        },
                        new
                        {
                            Id = 5,
                            FoodId = 103,
                            IngredientId = 10,
                            QuantityInGrams = 100.0
                        },
                        new
                        {
                            Id = 6,
                            FoodId = 103,
                            IngredientId = 5,
                            QuantityInGrams = 100.0
                        },
                        new
                        {
                            Id = 7,
                            FoodId = 103,
                            IngredientId = 6,
                            QuantityInGrams = 5.0
                        },
                        new
                        {
                            Id = 8,
                            FoodId = 104,
                            IngredientId = 7,
                            QuantityInGrams = 100.0
                        },
                        new
                        {
                            Id = 9,
                            FoodId = 104,
                            IngredientId = 8,
                            QuantityInGrams = 25.0
                        },
                        new
                        {
                            Id = 10,
                            FoodId = 105,
                            IngredientId = 11,
                            QuantityInGrams = 150.0
                        },
                        new
                        {
                            Id = 11,
                            FoodId = 105,
                            IngredientId = 9,
                            QuantityInGrams = 100.0
                        },
                        new
                        {
                            Id = 12,
                            FoodId = 107,
                            IngredientId = 2,
                            QuantityInGrams = 120.0
                        },
                        new
                        {
                            Id = 13,
                            FoodId = 107,
                            IngredientId = 4,
                            QuantityInGrams = 150.0
                        },
                        new
                        {
                            Id = 14,
                            FoodId = 108,
                            IngredientId = 13,
                            QuantityInGrams = 250.0
                        },
                        new
                        {
                            Id = 15,
                            FoodId = 108,
                            IngredientId = 3,
                            QuantityInGrams = 200.0
                        },
                        new
                        {
                            Id = 16,
                            FoodId = 109,
                            IngredientId = 2,
                            QuantityInGrams = 200.0
                        },
                        new
                        {
                            Id = 17,
                            FoodId = 109,
                            IngredientId = 14,
                            QuantityInGrams = 100.0
                        },
                        new
                        {
                            Id = 18,
                            FoodId = 109,
                            IngredientId = 12,
                            QuantityInGrams = 50.0
                        },
                        new
                        {
                            Id = 19,
                            FoodId = 110,
                            IngredientId = 1,
                            QuantityInGrams = 150.0
                        },
                        new
                        {
                            Id = 20,
                            FoodId = 110,
                            IngredientId = 5,
                            QuantityInGrams = 150.0
                        },
                        new
                        {
                            Id = 21,
                            FoodId = 110,
                            IngredientId = 12,
                            QuantityInGrams = 100.0
                        },
                        new
                        {
                            Id = 22,
                            FoodId = 111,
                            IngredientId = 15,
                            QuantityInGrams = 150.0
                        },
                        new
                        {
                            Id = 23,
                            FoodId = 111,
                            IngredientId = 16,
                            QuantityInGrams = 100.0
                        },
                        new
                        {
                            Id = 24,
                            FoodId = 111,
                            IngredientId = 5,
                            QuantityInGrams = 150.0
                        },
                        new
                        {
                            Id = 25,
                            FoodId = 111,
                            IngredientId = 6,
                            QuantityInGrams = 10.0
                        },
                        new
                        {
                            Id = 26,
                            FoodId = 112,
                            IngredientId = 18,
                            QuantityInGrams = 150.0
                        },
                        new
                        {
                            Id = 27,
                            FoodId = 112,
                            IngredientId = 8,
                            QuantityInGrams = 25.0
                        },
                        new
                        {
                            Id = 28,
                            FoodId = 113,
                            IngredientId = 17,
                            QuantityInGrams = 40.0
                        },
                        new
                        {
                            Id = 34,
                            FoodId = 114,
                            IngredientId = 16,
                            QuantityInGrams = 50.0
                        },
                        new
                        {
                            Id = 35,
                            FoodId = 114,
                            IngredientId = 21,
                            QuantityInGrams = 100.0
                        },
                        new
                        {
                            Id = 36,
                            FoodId = 115,
                            IngredientId = 7,
                            QuantityInGrams = 100.0
                        },
                        new
                        {
                            Id = 37,
                            FoodId = 115,
                            IngredientId = 12,
                            QuantityInGrams = 30.0
                        },
                        new
                        {
                            Id = 38,
                            FoodId = 116,
                            IngredientId = 5,
                            QuantityInGrams = 100.0
                        },
                        new
                        {
                            Id = 39,
                            FoodId = 116,
                            IngredientId = 14,
                            QuantityInGrams = 100.0
                        },
                        new
                        {
                            Id = 40,
                            FoodId = 116,
                            IngredientId = 6,
                            QuantityInGrams = 10.0
                        },
                        new
                        {
                            Id = 41,
                            FoodId = 117,
                            IngredientId = 23,
                            QuantityInGrams = 100.0
                        },
                        new
                        {
                            Id = 42,
                            FoodId = 117,
                            IngredientId = 24,
                            QuantityInGrams = 50.0
                        },
                        new
                        {
                            Id = 43,
                            FoodId = 117,
                            IngredientId = 1,
                            QuantityInGrams = 60.0
                        },
                        new
                        {
                            Id = 44,
                            FoodId = 117,
                            IngredientId = 22,
                            QuantityInGrams = 100.0
                        },
                        new
                        {
                            Id = 45,
                            FoodId = 118,
                            IngredientId = 1,
                            QuantityInGrams = 100.0
                        },
                        new
                        {
                            Id = 46,
                            FoodId = 118,
                            IngredientId = 12,
                            QuantityInGrams = 100.0
                        },
                        new
                        {
                            Id = 47,
                            FoodId = 118,
                            IngredientId = 24,
                            QuantityInGrams = 50.0
                        },
                        new
                        {
                            Id = 48,
                            FoodId = 118,
                            IngredientId = 14,
                            QuantityInGrams = 50.0
                        });
                });

            modelBuilder.Entity("Models.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CarbsPer100g")
                        .HasColumnType("float");

                    b.Property<double>("FatPer100g")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("bit");

                    b.Property<double>("KcalPer100g")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProteinPer100g")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarbsPer100g = 0.69999999999999996,
                            FatPer100g = 9.5,
                            ImageUrl = "aliment1.jpg",
                            IsVegan = false,
                            IsVegetarian = true,
                            KcalPer100g = 143.0,
                            Name = "Ou (buc)",
                            ProteinPer100g = 12.6
                        },
                        new
                        {
                            Id = 2,
                            CarbsPer100g = 0.0,
                            FatPer100g = 3.6000000000000001,
                            ImageUrl = "aliment2.jpg",
                            IsVegan = false,
                            IsVegetarian = false,
                            KcalPer100g = 165.0,
                            Name = "Piept de pui (crud)",
                            ProteinPer100g = 31.0
                        },
                        new
                        {
                            Id = 3,
                            CarbsPer100g = 28.0,
                            FatPer100g = 0.29999999999999999,
                            ImageUrl = "aliment3.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            KcalPer100g = 130.0,
                            Name = "Orez (fiert)",
                            ProteinPer100g = 2.7000000000000002
                        },
                        new
                        {
                            Id = 4,
                            CarbsPer100g = 6.5999999999999996,
                            FatPer100g = 0.40000000000000002,
                            ImageUrl = "aliment4.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            KcalPer100g = 34.0,
                            Name = "Broccoli",
                            ProteinPer100g = 2.7999999999999998
                        },
                        new
                        {
                            Id = 5,
                            CarbsPer100g = 3.8999999999999999,
                            FatPer100g = 0.20000000000000001,
                            ImageUrl = "aliment5.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            KcalPer100g = 18.0,
                            Name = "Roșii",
                            ProteinPer100g = 0.90000000000000002
                        },
                        new
                        {
                            Id = 6,
                            CarbsPer100g = 0.0,
                            FatPer100g = 100.0,
                            ImageUrl = "aliment6.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            KcalPer100g = 884.0,
                            Name = "Ulei de măsline",
                            ProteinPer100g = 0.0
                        },
                        new
                        {
                            Id = 7,
                            CarbsPer100g = 43.5,
                            FatPer100g = 3.5,
                            ImageUrl = "aliment7.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            KcalPer100g = 247.0,
                            Name = "Pâine integrală",
                            ProteinPer100g = 13.0
                        },
                        new
                        {
                            Id = 8,
                            CarbsPer100g = 20.0,
                            FatPer100g = 50.0,
                            ImageUrl = "aliment8.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            KcalPer100g = 588.0,
                            Name = "Unt de arahide",
                            ProteinPer100g = 25.0
                        },
                        new
                        {
                            Id = 9,
                            CarbsPer100g = 23.0,
                            FatPer100g = 0.29999999999999999,
                            ImageUrl = "aliment9.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            KcalPer100g = 89.0,
                            Name = "Banane",
                            ProteinPer100g = 1.1000000000000001
                        },
                        new
                        {
                            Id = 10,
                            CarbsPer100g = 0.0,
                            FatPer100g = 0.80000000000000004,
                            ImageUrl = "aliment10.jpg",
                            IsVegan = false,
                            IsVegetarian = false,
                            KcalPer100g = 116.0,
                            Name = "Ton în apă",
                            ProteinPer100g = 25.5
                        },
                        new
                        {
                            Id = 11,
                            CarbsPer100g = 4.0,
                            FatPer100g = 2.0,
                            ImageUrl = "aliment11.jpg",
                            IsVegan = false,
                            IsVegetarian = true,
                            KcalPer100g = 73.0,
                            Name = "Iaurt grecesc (2%)",
                            ProteinPer100g = 10.0
                        },
                        new
                        {
                            Id = 12,
                            CarbsPer100g = 8.5,
                            FatPer100g = 14.0,
                            ImageUrl = "aliment12.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            KcalPer100g = 160.0,
                            Name = "Avocado",
                            ProteinPer100g = 2.0
                        },
                        new
                        {
                            Id = 13,
                            CarbsPer100g = 23.699999999999999,
                            FatPer100g = 0.5,
                            ImageUrl = "aliment13.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            KcalPer100g = 139.0,
                            Name = "Fasole neagră (conservă)",
                            ProteinPer100g = 8.9000000000000004
                        },
                        new
                        {
                            Id = 14,
                            CarbsPer100g = 2.2000000000000002,
                            FatPer100g = 14.0,
                            ImageUrl = "aliment14.jpg",
                            IsVegan = false,
                            IsVegetarian = true,
                            KcalPer100g = 250.0,
                            Name = "Mozzarella (low-fat)",
                            ProteinPer100g = 28.0
                        },
                        new
                        {
                            Id = 15,
                            CarbsPer100g = 21.0,
                            FatPer100g = 1.8999999999999999,
                            ImageUrl = "aliment15.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            KcalPer100g = 120.0,
                            Name = "Quinoa (fiartă)",
                            ProteinPer100g = 4.4000000000000004
                        },
                        new
                        {
                            Id = 16,
                            CarbsPer100g = 27.0,
                            FatPer100g = 2.6000000000000001,
                            ImageUrl = "aliment16.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            KcalPer100g = 164.0,
                            Name = "Năut (conservă)",
                            ProteinPer100g = 8.9000000000000004
                        },
                        new
                        {
                            Id = 17,
                            CarbsPer100g = 42.0,
                            FatPer100g = 31.0,
                            ImageUrl = "aliment17.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            KcalPer100g = 486.0,
                            Name = "Semințe de Chia",
                            ProteinPer100g = 17.0
                        },
                        new
                        {
                            Id = 18,
                            CarbsPer100g = 14.0,
                            FatPer100g = 0.20000000000000001,
                            ImageUrl = "aliment18.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            KcalPer100g = 52.0,
                            Name = "Măr",
                            ProteinPer100g = 0.29999999999999999
                        },
                        new
                        {
                            Id = 19,
                            CarbsPer100g = 22.0,
                            FatPer100g = 50.0,
                            ImageUrl = "aliment19.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            KcalPer100g = 579.0,
                            Name = "Migdale",
                            ProteinPer100g = 21.0
                        },
                        new
                        {
                            Id = 20,
                            CarbsPer100g = 3.0,
                            FatPer100g = 1.0,
                            ImageUrl = "aliment20.jpg",
                            IsVegan = false,
                            IsVegetarian = true,
                            KcalPer100g = 72.0,
                            Name = "Brânză Cottage (degresată)",
                            ProteinPer100g = 12.0
                        },
                        new
                        {
                            Id = 21,
                            CarbsPer100g = 9.5999999999999996,
                            FatPer100g = 0.20000000000000001,
                            ImageUrl = "aliment21.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            KcalPer100g = 41.0,
                            Name = "Morcov",
                            ProteinPer100g = 0.90000000000000002
                        },
                        new
                        {
                            Id = 22,
                            CarbsPer100g = 3.1000000000000001,
                            FatPer100g = 30.0,
                            ImageUrl = "aliment22.jpg",
                            IsVegan = false,
                            IsVegetarian = true,
                            KcalPer100g = 292.0,
                            Name = "Smântână (30%)",
                            ProteinPer100g = 2.5
                        },
                        new
                        {
                            Id = 23,
                            CarbsPer100g = 75.0,
                            FatPer100g = 1.5,
                            ImageUrl = "aliment23.jpg",
                            IsVegan = true,
                            IsVegetarian = true,
                            KcalPer100g = 371.0,
                            Name = "Paste (uscate)",
                            ProteinPer100g = 13.0
                        },
                        new
                        {
                            Id = 24,
                            CarbsPer100g = 1.5,
                            FatPer100g = 42.0,
                            ImageUrl = "aliment24.jpg",
                            IsVegan = false,
                            IsVegetarian = false,
                            KcalPer100g = 541.0,
                            Name = "Bacon",
                            ProteinPer100g = 37.0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Entities.ApplicationUser", b =>
                {
                    b.OwnsOne("Models.Entities.Target", "Target", b1 =>
                        {
                            b1.Property<string>("ApplicationUserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("DailyCarbs")
                                .HasColumnType("float");

                            b1.Property<double>("DailyFat")
                                .HasColumnType("float");

                            b1.Property<double>("DailyKcal")
                                .HasColumnType("float");

                            b1.Property<double>("DailyProtein")
                                .HasColumnType("float");

                            b1.HasKey("ApplicationUserId");

                            b1.ToTable("AspNetUsers");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationUserId");
                        });

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Models.Entities.DailyLog", b =>
                {
                    b.HasOne("Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Models.Entities.DailyLogMeal", b =>
                {
                    b.HasOne("Models.Entities.DailyLog", "DailyLog")
                        .WithMany("Meals")
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyLog");
                });

            modelBuilder.Entity("Models.Entities.DailyLogRecipe", b =>
                {
                    b.HasOne("Models.Entities.DailyLogMeal", "DailyLogMeal")
                        .WithMany("Recipes")
                        .HasForeignKey("DailyLogMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyLogMeal");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("Models.Entities.FoodIngredient", b =>
                {
                    b.HasOne("Models.Entities.Food", "Food")
                        .WithMany("Ingredients")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Models.Entities.DailyLog", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("Models.Entities.DailyLogMeal", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Models.Entities.Food", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
